name: Health Check

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Check Production Environment
        id: check_prod
        run: |
          set +e # Allow curl to fail without exiting the script
          CURL_OUTPUT=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.PROD_URL }}/api/health 2>&1)
          HTTP_CODE=$(echo $CURL_OUTPUT | tail -n 1)
          CURL_ERROR=$(echo $CURL_OUTPUT | head -n -1)

          if [ "$HTTP_CODE" -ne 200 ]; then
            echo "Production environment is down! HTTP Code: $HTTP_CODE"
            echo "PROD_DOWN=true" >> $GITHUB_ENV
            echo "PROD_ERROR=$CURL_ERROR" >> $GITHUB_ENV
          else
            echo "Production environment is up. HTTP Code: $HTTP_CODE"
          fi

      - name: Check Development Environment
        id: check_dev
        run: |
          set +e # Allow curl to fail without exiting the script
          CURL_OUTPUT=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.DEV_URL }}/api/health 2>&1)
          HTTP_CODE=$(echo $CURL_OUTPUT | tail -n 1)
          CURL_ERROR=$(echo $CURL_OUTPUT | head -n -1)

          if [ "$HTTP_CODE" -ne 200 ]; then
            echo "Development environment is down! HTTP Code: $HTTP_CODE"
            echo "DEV_DOWN=true" >> $GITHUB_ENV
            echo "DEV_ERROR=$CURL_ERROR" >> $GITHUB_ENV
          else
            echo "Development environment is up. HTTP Code: $HTTP_CODE"
          fi

      - name: Create Issue on Failure
        if: env.PROD_DOWN == 'true' || env.DEV_DOWN == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let body = ''
            if (process.env.PROD_DOWN === 'true') {
              body += 'Production environment is down!\n'
              if (process.env.PROD_ERROR) {
                body += `cURL Error: ${process.env.PROD_ERROR}\n`
              }
            }
            if (process.env.DEV_DOWN === 'true') {
              body += 'Development environment is down!\n'
              if (process.env.DEV_ERROR) {
                body += `cURL Error: ${process.env.DEV_ERROR}\n`
              }
            }
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Application Health Check Failed',
              body: body
            });